#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Launch an application on the specified monitor.

import argparse

import common
from feeders import dmenu_path as feeder
from i3_actions import launch_app


PARSER = argparse.ArgumentParser(prog='dmenu_run')
common.add_monitor_param(PARSER)

PARSER.add_argument('-f', '--free',
                    action='store_true',
                    default=False,
                    help=('If true the application is launched on a free '
                          'workspace.'))


if __name__ == '__main__':
    args = PARSER.parse_args()
    mon = common.get_monitor_value(args)
    launch_app(feeder, mon, args.free)
