#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Send the current window to a the visible workspace on the next output.

import argparse

import common
from feeders import free_workspaces as feeder
from i3_actions import send_window_to_visible_workspace


PARSER = argparse.ArgumentParser(prog='dmenu_send_win_to_visible_workspace')
common.add_monitor_param(PARSER)

if __name__ == '__main__':
    args = PARSER.parse_args()
    send_window_to_visible_workspace(feeder)
