#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Go to the selected i3 window

from feeders import windows as feeder
from i3_actions import jump_to_window

if __name__ == '__main__':
    jump_to_window(feeder)
