#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Send the current window to the workspace of the chosen window

from feeders import windows as feeder
from i3_actions import send_window_to_win_workspace


if __name__ == '__main__':
    send_window_to_win_workspace(feeder)