#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Logout from the session

import os
from subprocess import Popen

import dmenu
from constants import DMENU_FONT, DMENU_HEIGHT
from feeders import logout, confirm

MODULE_PATH = os.path.dirname(os.path.abspath(__file__))


def prompt_user(feeder, prompt):
    p = ''
    if prompt:
        p = feeder.get_prompt(prompt)
    else:
        p = feeder.get_prompt()
    proc = dmenu.call(p=p,
                      f=DMENU_FONT,
                      h=DMENU_HEIGHT,
                      nb='#cb4b16',
                      nf='#eee8dc',
                      sb='#002b36',
                      sf='#eee8d5')
    return proc.communicate('\n'.join(feeder.feed()).encode('utf-8'))[0]


if __name__ == '__main__':
    reply = prompt_user(logout, None)
    if reply and prompt_user(confirm, reply) == 'OK':
        exec_ = os.path.join(MODULE_PATH, 'i3-exit')
        cmd = '{0} --{1}'.format(exec_, reply)
        Popen(cmd, shell=True)
