#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Send the current workspace to a monitor

from feeders import outputs as feeder
from i3_actions import send_workspace_to_output


if __name__ == '__main__':
    send_workspace_to_output(feeder)
