#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Set layout.

import argparse

from feeders import i3cmd as feeder
from i3_actions import execute_cmd


PARSER = argparse.ArgumentParser(prog='dmenu_i3_cmd')
PARSER.add_argument('-p', '--prefix',
                    default=None,
                    help='Command prefix.')

if __name__ == '__main__':
    args = PARSER.parse_args()
    execute_cmd(feeder, args.prefix)
