#!/usr/bin/env python

# author: syl20bnr (2013)
# goal: Set layout.

from feeders import layouts as feeder
from i3_actions import execute_layout_cmd

if __name__ == '__main__':
    execute_layout_cmd(feeder)
